version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    networks:
      - inception
    ports: 
      - "9000:9000"
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kali/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/kali/data/wordpress'

networks:
  inception:
    driver: bridge