version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    env_file:
      - .env

#name image for each containers
# volumes:
#   mariadb:
#     driver: local
#     driver_opts:
#       type: 'none'
#       o: 'bind'
#       device: /home/slepetit/data/mariadb